module.exports = {
  businessInfo: {
    id: "12311",
    name: "Coffie",
    type: "Coffee Shop",
    address: "3221 LaSalle St",
    state: "IL",
    city: "Chicago",
    zip: "60001",
    country: "USA",
    contact1: "Jackson Polluck",
    contact2: "Salvi Doriani",
    contact3: "",
    phone1: "(408) 332 - 4432",
    phone2: "(605) 954 - 1009",
    phone3: "",
    fax1: "(530) 210 - 2122",
    fax2: "",
    fax3: "",
    email1: "coffie@coffie.co",
    email2: "",
    email3: "",
    posTitle: "Cafe Coffie Co",
    websiteURL: "www.coffie.co",
    supportContact: "Amy Polar",
    supportPhone: "(291) 300 - 3221",
    supportEmail: "support@coffie.com",
    supportURL: "www.coffie.co/support",
  },
  user1: {
    id: 1,
    userName: "gat",
    firstName: "Prathmesh",
    lastName: "Gat",
    passwordHash: "gat",
    passwordSalt: "",
    token: "",
    tokenStartTime: "",
    tokenEndTime: "",
    accessCode: "",
    role: "",
    isEnabled: "",
    addressLine1: "",
    addressLine2: "",
    city: "",
    state: "",
    street: "",
    zip: "",
    county: "",
    phone1: "",
    phone2: "",
    phone3: "",
    email1: "",
    email2: "",
    website1: "",
    website2: "",
    notes: "",
    secretQuestion1: "",
    secretAnswer1: "",
    secretQuestion2: "",
    secretAnswer2: "",
    secretQuestion3: "",
    secretAnswer3: "",
    pictureURL: "",
    bestTimeToCall: "",
    status: "",
    language: "",
    custom1: "",
    custom2: "",
    custom3: "",
    custom4: "",
    custom5: "",
    custom6: "",
    custom7: "",
    custom8: "",
    custom9: "",
    custom10: "",
  },
  user2: {
    id: 2,
    userName: "frey",
    firstName: "Conner",
    lastName: "Frey",
    passwordHash: "frey",
    passwordSalt: "",
    token: "",
    tokenStartTime: "",
    tokenEndTime: "",
    accessCode: "",
    role: "",
    isEnabled: "",
    addressLine1: "",
    addressLine2: "",
    city: "",
    state: "",
    street: "",
    zip: "",
    county: "",
    phone1: "",
    phone2: "",
    phone3: "",
    email1: "",
    email2: "",
    website1: "",
    website2: "",
    notes: "",
    secretQuestion1: "",
    secretAnswer1: "",
    secretQuestion2: "",
    secretAnswer2: "",
    secretQuestion3: "",
    secretAnswer3: "",
    pictureURL: "",
    bestTimeToCall: "",
    status: "",
    language: "",
    custom1: "",
    custom2: "",
    custom3: "",
    custom4: "",
    custom5: "",
    custom6: "",
    custom7: "",
    custom8: "",
    custom9: "",
    custom10: "",
  }
};
