var items1 = [
  {
    id: 3292,
    name: "Cappuccino",
    upc: "8934utgbmi52941mfqwerqr0",
    imgUrl: "https://",
    thumbUrl: "https://",
    description: "",
    color: "",
    type: "",
    status: "active",
    price: "4785",
    priceIsFixed: false,
    priceIsPercent: false,
    priceAllowsDecimal: true,
    quantity: 1,
    quantityIsFixed: false,
    quantityAllowsDecimal: false,
    unit: "dozen",
  },
  {
    id: 4920,
    name: "Frappuccino",
    upc: "8934utgbmi52941mfqwerqr0",
    imgUrl: "https://",
    thumbUrl: "https://",
    description: "",
    color: "",
    type: "",
    status: "active",
    price: "932",
    priceIsFixed: false,
    priceIsPercent: false,
    priceAllowsDecimal: true,
    quantity: 1,
    quantityIsFixed: false,
    quantityAllowsDecimal: false,
    unit: "half dozen",
  },
  {
    id: 8493,
    name: "Mocha",
    upc: "8934utgbmi52941mfqwerqr0",
    imgUrl: "https://",
    thumbUrl: "https://",
    description: "",
    color: "",
    type: "",
    status: "active",
    price: "2320",
    priceIsFixed: false,
    priceIsPercent: false,
    priceAllowsDecimal: true,
    quantity: 1,
    quantityIsFixed: false,
    quantityAllowsDecimal: false,
    unit: "half dozen",
  },
  {
    id: 4877,
    name: "Americano",
    upc: "8934utgbmi52941mfqwerqr0",
    imgUrl: "https://",
    thumbUrl: "https://",
    description: "",
    color: "",
    type: "",
    status: "active",
    price: "2320",
    priceIsFixed: false,
    priceIsPercent: false,
    priceAllowsDecimal: true,
    quantity: 1,
    quantityIsFixed: false,
    quantityAllowsDecimal: false,
    unit: "one",
  },
  {
    id: 1233,
    name: "Hot Coacoa",
    upc: "8934utgbmi52941mfqwerqr0",
    imgUrl: "https://",
    thumbUrl: "https://",
    description: "",
    color: "",
    type: "",
    status: "active",
    price: "2320",
    priceIsFixed: false,
    priceIsPercent: false,
    priceAllowsDecimal: true,
    quantity: 1,
    quantityIsFixed: false,
    quantityAllowsDecimal: false,
    unit: "one",
  }
];

var items2 = [
  {
    id: 38,
    name: "Starfruit",
    upc: "8934utgbmi52941mfqwerqr0",
    imgUrl: "https://",
    thumbUrl: "https://",
    description: "",
    color: "",
    type: "",
    status: "active",
    price: "4785",
    priceIsFixed: false,
    priceIsPercent: false,
    priceAllowsDecimal: true,
    quantity: 1,
    quantityIsFixed: false,
    quantityAllowsDecimal: false,
    unit: "dozen",
  },
  {
    id: 39,
    name: "Cherries",
    upc: "8934utgbmi52941mfqwerqr0",
    imgUrl: "https://",
    thumbUrl: "https://",
    description: "",
    color: "",
    type: "",
    status: "active",
    price: "932",
    priceIsFixed: false,
    priceIsPercent: false,
    priceAllowsDecimal: true,
    quantity: 1,
    quantityIsFixed: false,
    quantityAllowsDecimal: false,
    unit: "half dozen",
  },
  {
    id: 40,
    name: "Blackberries",
    upc: "8934utgbmi52941mfqwerqr0",
    imgUrl: "https://",
    thumbUrl: "https://",
    description: "",
    color: "",
    type: "",
    status: "active",
    price: "2320",
    priceIsFixed: false,
    priceIsPercent: false,
    priceAllowsDecimal: true,
    quantity: 1,
    quantityIsFixed: false,
    quantityAllowsDecimal: false,
    unit: "half dozen",
  },
  {
    id: 41,
    name: "Blueberries",
    upc: "8934utgbmi52941mfqwerqr0",
    imgUrl: "https://",
    thumbUrl: "https://",
    description: "",
    color: "",
    type: "",
    status: "active",
    price: "2320",
    priceIsFixed: false,
    priceIsPercent: false,
    priceAllowsDecimal: true,
    quantity: 1,
    quantityIsFixed: false,
    quantityAllowsDecimal: false,
    unit: "one",
  },
  {
    id: 42,
    name: "Strawberries",
    upc: "8934utgbmi52941mfqwerqr0",
    imgUrl: "https://",
    thumbUrl: "https://",
    description: "",
    color: "",
    type: "",
    status: "active",
    price: "2320",
    priceIsFixed: false,
    priceIsPercent: false,
    priceAllowsDecimal: true,
    quantity: 1,
    quantityIsFixed: false,
    quantityAllowsDecimal: false,
    unit: "one",
  },
  {
    id: 43,
    name: "Cranberries",
    upc: "8934utgbmi52941mfqwerqr0",
    imgUrl: "https://",
    thumbUrl: "https://",
    description: "",
    color: "",
    type: "",
    status: "active",
    price: "2320",
    priceIsFixed: false,
    priceIsPercent: false,
    priceAllowsDecimal: true,
    quantity: 1,
    quantityIsFixed: false,
    quantityAllowsDecimal: false,
    unit: "one",
  },
  {
    id: 44,
    name: "Pineapples",
    upc: "8934utgbmi52941mfqwerqr0",
    imgUrl: "https://",
    thumbUrl: "https://",
    description: "",
    color: "",
    type: "",
    status: "active",
    price: "2320",
    priceIsFixed: false,
    priceIsPercent: false,
    priceAllowsDecimal: true,
    quantity: 1,
    quantityIsFixed: false,
    quantityAllowsDecimal: false,
    unit: "one",
  }
];

module.exports = {
  selectedItem: {},
  selectedCategory: {
    id: 4022,
    name: "Coffee",
    color: "green",
    displayOrder: 1,
    status: "active",
    imgUrl: "http://",
    description: "",
  },
  categories: [
    {
      id: 4022,
      name: "Coffee",
      color: "green",
      displayOrder: 1,
      status: "active",
      imgUrl: "http://",
      description: "",
      items: items1
    },
    {
      id: 2012,
      name: "Fruit",
      color: "blue",
      displayOrder: 2,
      status: "active",
      imgUrl: "http://",
      description: "",
      items: items2
    },
    {
      id: 9533,
      name: "Veggies",
      color: "red",
      displayOrder: 3,
      status: "active",
      imgUrl: "http://",
      description: "",
    },
    {
      id: 1933,
      name: "Cookies",
      color: "orange",
      displayOrder: 4,
      status: "active",
      imgUrl: "http://",
      description: "",
    },
    {
      id: 5738,
      name: "Other",
      color: "yellow",
      displayOrder: 5,
      status: "active",
      imgUrl: "http://",
      description: "",
    },

  ],
  checkoutItems: [], // this should be empty
};
